# Generated by Django 4.1 on 2022-09-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='temp_measurement',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
